### PR TITLE
Support ASM7, after upgrading to jdk11

### PR DESCRIPTION
**Pull request by amihaihalevy**

### CODE REVIEW

**Comment by amihaihalevy** [comment]
@rlewellen-salesforce can you review this one? There are some tests that rely on it.

**Comment by rexhoffman** [comment]
Looks like I'll need to bump the CI system's java versions as well.

**Comment by amihaihalevy** [comment]
Anything that I need to do from my side?

**Comment by amihaihalevy** [comment]
@rexhoffman can you merge the change? I see that you already updated the CI with the java versions.
Thanks

**Comment by amihaihalevy** [comment]
Hi @rexhoffman 
Any update? we would like to merge the changes.
Thanks

**Comment by binzywu** [comment]
@rexhoffman would appreciate if this can be merged.

fyi @rlewellen-salesforce

**Pull request merged**
